security:
    encoders:
        App\Bundle\LoginAndACLBundle\Entity\User: bcrypt
    providers:
        in_memory:
            memory: ~
        user_from_db:
            entity:
                class: App\Bundle\LoginAndACLBundle\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                provider: user_from_db
                login_path: /login
                check_path: /login_check
                default_target_path: acl_login_homepage # login after successfull login
            logout:
                path: /logout
                target: /